### ISSUE TITLE
Breakpoints need restart of IntelliJ to appear, and takes several seconds to add

### ISSUE THREAD

**Issue by emeli-fransson-2-wcar** [maximehamm/tzatziki#15] opened 2021-09-10 06:48 UTC
Using Cucumber+ 9.0.3 and IntelliJ 2021.2.1 Community

Breakpoints do not appear when clicking in gutter in Gherkin files, or by pressing Ctrl+F8. I was able to get a breakpoint to appear in the Gherkin file by adding it to the implementation and restarting IntellJ, then a breakpoint would appear in the Gherkin file as well. A restart of IntelliJ is needed to remove the breakpoint as well. Also. adding or removing a breakpoint in the implementation takes several seconds.

Other than that, great plugin!

**Comment by maximehamm** [comment] 2021-09-12 19:04
Hello Emili
Which language are you using ? Java or Kotlin ?
Does it happen always or sometimes ?

**Comment by emeli-fransson-2-wcar** [comment] 2021-09-14 11:13
Hi,
I'm using Java and it happens always

**Comment by maximehamm** [comment] 2021-10-03 12:18
Hi
I'm disappointed... I'm unable to reproduce this issue... 
I've fixed another issue reported by someone else... may be it is related to this... can you check with version 9.1.x ? Is there some error logs available from "event log" window ? 
Maxime

**Comment by maximehamm** [comment] 2021-12-10 08:26
Hi Emili
Do you still use Cucumber+ ? I've fixed some issue in the version 9.2.0 which might fix this... can you tell me please ?
Maxime

**Comment by maximehamm** [comment] 2021-12-15 14:34
Il think it should be fixed... let me know if not !

**Comment by maximehamm** [comment] 2021-12-16 12:47
Oups, I just found that the problem occurs on another PC of mine... let's investigate it !

**Closed** 2022-01-03 15:40 UTC
